version: '3'
services:
  app:
    container_name: app
    build: ./backend
    env_file:
      - backend/.env
    restart: unless-stopped
    depends_on:
      - db
    networks:
      - backend
      - frontend

  db:
    image: mysql:8
    container_name: db
    restart: unless-stopped
    volumes:
      - orders-data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: orders_management
      MYSQL_ROOT_PASSWORD: 12345678
    networks:
      - backend

  nginx:
    build: ./nginx
    container_name: nginx
    ports:
      - 8087:80
    volumes:
      - ./backend/templates:/usr/share/nginx/html
      - ./backend/static:/usr/share/nginx/html/static
    depends_on:
      - app
    restart: always
    networks:
      - frontend
    
volumes:
  orders-data:
    driver: local

networks:
  backend:
  frontend: